[package]
name = "ecriture-libre"
version = "1.0.0"
edition = "2021"
authors = ["Julien Mourer"]
description = "Chaque mot, une fois écrit, ne peut pas être supprimé"

[dependencies]
nix = "0.23"
clap = { version = "3.0", features = ["derive"] }
chrono = "0.4"
